/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultRouteImport } from './routes/result'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DetailsRouteImport } from './routes/details'
import { Route as DecisionRouteImport } from './routes/decision'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as AlternativesRouteImport } from './routes/alternatives'
import { Route as IndexRouteImport } from './routes/index'

const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailsRoute = DetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionRoute = DecisionRouteImport.update({
  id: '/decision',
  path: '/decision',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const AlternativesRoute = AlternativesRouteImport.update({
  id: '/alternatives',
  path: '/alternatives',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alternatives': typeof AlternativesRoute
  '/connect': typeof ConnectRoute
  '/decision': typeof DecisionRoute
  '/details': typeof DetailsRoute
  '/home': typeof HomeRoute
  '/result': typeof ResultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alternatives': typeof AlternativesRoute
  '/connect': typeof ConnectRoute
  '/decision': typeof DecisionRoute
  '/details': typeof DetailsRoute
  '/home': typeof HomeRoute
  '/result': typeof ResultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alternatives': typeof AlternativesRoute
  '/connect': typeof ConnectRoute
  '/decision': typeof DecisionRoute
  '/details': typeof DetailsRoute
  '/home': typeof HomeRoute
  '/result': typeof ResultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alternatives'
    | '/connect'
    | '/decision'
    | '/details'
    | '/home'
    | '/result'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alternatives'
    | '/connect'
    | '/decision'
    | '/details'
    | '/home'
    | '/result'
  id:
    | '__root__'
    | '/'
    | '/alternatives'
    | '/connect'
    | '/decision'
    | '/details'
    | '/home'
    | '/result'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlternativesRoute: typeof AlternativesRoute
  ConnectRoute: typeof ConnectRoute
  DecisionRoute: typeof DecisionRoute
  DetailsRoute: typeof DetailsRoute
  HomeRoute: typeof HomeRoute
  ResultRoute: typeof ResultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/details': {
      id: '/details'
      path: '/details'
      fullPath: '/details'
      preLoaderRoute: typeof DetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decision': {
      id: '/decision'
      path: '/decision'
      fullPath: '/decision'
      preLoaderRoute: typeof DecisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alternatives': {
      id: '/alternatives'
      path: '/alternatives'
      fullPath: '/alternatives'
      preLoaderRoute: typeof AlternativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlternativesRoute: AlternativesRoute,
  ConnectRoute: ConnectRoute,
  DecisionRoute: DecisionRoute,
  DetailsRoute: DetailsRoute,
  HomeRoute: HomeRoute,
  ResultRoute: ResultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
